name: Build

on:
  push:
    branches: [master]

env:
  IMAGE: test

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    outputs:
      image-name: ${{ steps.set-image-name.outputs.image-name }}
      image-sha: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set image name
      id: set-image-name
      run: echo "image-name=gcr.io/placeholder-image-name" >> $GITHUB_OUTPUT

    - name: Build
      run: |-
        docker build \
          --tag "${{ steps.set-image-name.outputs.image-name }}:develop-${{ github.sha }}" \
          --build-arg GITHUB_SHA="${{ github.sha }}" \
          --build-arg GITHUB_REF="${{ github.ref }}" \
          .

